[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.optimized"
buildCommand = ""

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
